sudo: false
language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email:
    on_failure: change

node_js:
  - '8.9.4'

before_script:
  - npm prune

script:
  - npm run build
  - npm run test
